### ISSUE TITLE
TLS failed to start the connection process. Error: io_open failed

### ISSUE THREAD

**Issue by mysaggar** [Azure-Samples/iot-hub-c-huzzah-getstartedkit#24]
I am working with ADAFRUIT FEATHER HUZZAH board esp8266 and am receiving this error : 

> connected with Moriarty, channel 11
dhcp client start...
ip:192.168.43.126,mask:255.255.255.0,gw:192.168.43.1
Connected to wifi Moriarty.
Fetched NTP epoch time is: 28812.
result = IOTHUB_CLIENT_OK
Sending message: {"deviceId":"Feather HUZZAH ESP8266 WiFi","messageId":1,"temperature":28,"humidity":36}.
IoTHubClient accepted the message for delivery.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.
TLS failed to start the connection process.

The library versions and board versions are upto date except the ArduinoJson Library which is at 5.13.4 (gives compilation errors with latest library).

Used NodeMCU Esp8266 board too it isn't hardware related and also the I have double checked my Connection Strings.

**Comment by mysaggar** [comment]
On discussion with @YoDaMa I found out that the current board library version 2.5.0 sets BearSSL as the default SSL/TSL Library and has unresloved issues with it. Recommendations were to roll back the Board library version to the point before BearSSL uses older axTLS, works with 2.4.2.

**Comment by Elgaatoo** [comment]
@mysaggar I'm having similar Problems with my Adafruit ESP8266 board. Were you able to solve the TLS connection problem?

**Comment by jantenhove** [comment]
@Elgaatoo I had succes with the workaround from: https://github.com/Azure/azure-iot-arduino/issues/89
